language: Java
sudo: required
jdk:
- oraclejdk8
before_install:
- pip install --user codecov
after_success:
- codecov
- ./gradlew sonarqube
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
deploy:
  provider: heroku
  api_key:
    secure: H/X090CPZE0wXg8EShGHBIM4N5SDrnGQ3Tl130NajS1iQfEGa6RrLffgMqRpsanh0NnYh/9lURYklWnoV+mPnx+pxBBzdkb3Te0xXjmGtJhjiP7d3IKfVxkYteJ4R914HELq9IFrW8gkfpNrdtgThZcx3CqhXQRbUCKAHtgmJbOKpLFhtJtpFq3Ag0vRPImtT+4Vc3git/vNetrXsGSjZUigqxeHGIYSB5EVgLCvtodb4caZSds2HFnJ8S0oUudzkhqNG9BtRczFs0HEVs4ToQKHJrqTNr6HgXwtpK4a+v5tumh5Uz60vb/taavL7w7MgmEzdRqGvP3z3gYl+NqsyxBBdLiB8kIx3LFNpEqB/1p06xNfC3TI8hosHmCltmWHi0Jt9OUD5QntVZbFTyjQ1FTP6p7YZWOV3GOlqMOmLKea1M8PP3E7y6Gqil66+x7TzejDm4M5dFyciFvlRZg0OiAv5PuAzb8r7T1s9iJ+iP9sEV638laY544hvTse0qyJl6GHX+q2i29PaorIepk1bXm53at/9u3Ck5517AzopIZvtyMvv0DE08RoVqVzmMU6E7lfCCeUwsaoBS+F1g5CuQ6XvoltfxRM2zfdtHbAU7URVNmfiwGK7jf34tKmgmxSO4bfvF+VsSUs0/sum3jP0E5jpg0Cc/7qJgs/CfcFUkA=
  app: confirmation-sender-staging
  skip_cleanup: true
  on:
    repo: spolnik/trading-office-confirmation-sender
services:
- rabbitmq