server:
  port: 9002
endpoints:
  jmx:
    unique-names: true

feign:
  hystrix:
    enabled: false

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80